server:
  servlet:
    context-path: /carbon-scaffold

spring:
  application:
    name: carbon-scaffold
  datasource:
    url: jdbc:mysql://localhost:3306/carbon-scaffold
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678

mybatis:
  check-config-location: true
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

carbon:
  i18n:
    fallback-language-only: true
    datasource:
      index: local
      source: local