# Development Environment Config
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/carbon-scaffold
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12345678

carbon:
  i18n:
    fallback-language-only: true
    datasource:
      index: local
      source: local

springfox:
  documentation:
    swagger-ui:
      enabled: true